package com.saaei12092021.office.model.responseModel.update_password_response

data class User(
    val accountType: String,
    val adsCount: Int,
    val adsPackage: AdsPackage,
    val approved: Boolean,
    val availableAds: Int,
    val blockReason: String,
    val city: City,
    val commercialFile: String,
    val completProfile: Boolean,
    val country: Country,
    val createdAt: String,
    val deleted: Boolean,
    val email: String,
    val enableNotif: Boolean,
    val fullname: String,
    val hasAdsPackage: Boolean,
    val hasPropertyPackage: Boolean,
    val id: Int,
    val img: String,
    val isVerified: Boolean,
    val online: Boolean,
    val packageEndDateMillSec: Long,
    val packageStartDateMillSec: Long,
    val phone: String,
    val rate: Int,
    val type: String,
    val updatedAt: String,
    val viewsCount: Int,
    val workArea: List<WorkArea>,
    val workCategory: List<WorkCategory>,
    val workCity: List<WorkCity>,
    val workSubCategory: List<WorkSubCategory>
)