package com.saaei12092021.office.model.responseModel.getUserByTokenResponse

import java.io.Serializable

data class User(
    val accountType: String,
    val adNumber: String,
    val adsCount: Int,
    val adsPackage: AdsPackage,
    val agencyType: String,
    val approved: Boolean,
    val availableAds: Int,
    val availableProperty: Int,
    val blockReason: String,
    val city: City,
    val commercialFile: List<String>,
    val country: Country,
    val createdAt: String,
    val deleted: Boolean,
    val email: String,
    val enableNotif: Boolean,
    val fullname: String,
    val hasAdsPackage: Boolean,
    val hasPropertyPackage: Boolean,
    val id: Int,
    val idNumber: String,
    val idType: String,
    val img: String,
    val isMarketPlace: Boolean,
    val isVerified: Boolean,
    val lastSeen: Long,
    val marketPlace: MarketPlace?,
    val online: Boolean,
    val packageEndDateMillSec: Long,
    val packageStartDateMillSec: Long,
    val phone: String,
    val propertyPackage: PropertyPackage,
    val propertyPackageEndDateMillSec: Long,
    val propertyPackageStartDateMillSec: Long,
    val rate: Int,
    val type: String,
    val updatedAt: String,
    val viewsCount: Int,
    val workArea: List<WorkArea>,
    val workCategory: List<WorkCategory>,
    val workCity: List<WorkCity>,
    val workSubCategory: List<WorkSubCategory>
): Serializable