package com.saaei12092021.office.model.responseModel.adRequestedByIdResponse

data class Advertisement(
    val area: List<Area>? = null,
    val available: Boolean,
    val category: Category,
    val city: City,
  //  val contactsOffices: List<Any>,
    val contractType: String,
    val rentType : String ? ,
    val createdAt: String,
    val dateMilleSec: Long,
    val description: String,
    val description_ar: String,
    val description_en: String,
    val enableInstallment: Boolean,
    val enablePhoneContact: Boolean,
    val features: List<Feature>,
    val id: Int,
    val contactsOffices : ArrayList<Int>? = null ,
    val isConnected: Boolean,
    val newContactRequest: Int,
    val owner: Owner,
    val priceFrom: Any,
    val priceType: String,
    val properties: List<Property>,
 //   val refusedOffices: List<Any>,
    val sizeFrom: Any,
    val sizeTo: Any,
    val status: String,
    val subCategory: SubCategory,
    val title: String,
    val title_ar: String,
    val title_en: String,
  // val withdrawOffices: List<Int>
)