package com.saaei12092021.office.model.responseModel.adsById

import java.io.Serializable

data class Advertisement(
    val adNumber : String? ,
    val address: String,
    val address_ar: String,
    val address_en: String,
    //  val adsFile: List<String>?,
    val advertiserClass: String,
    val area: Area,
    val streetName : String ? ,
    val available: Boolean,
    val viewsCount : Int ,
    val bestFeature: String,
    val bestFeature_ar: String,
    val bestFeature_en: String,
    val category: Category,
    val city: City,
    val commissionNumber: String,
    val contractType: String,
    val rentType: String?,
    val contraindications: Boolean,
    val contraindicationsDesc: String,
    val createdAt: String,
    val dateMilleSec: Long,
    val contactsOffices: ArrayList<Int>? = null,
    val deposit: Double ,
    val description: String,
    val description_ar: String,
    val description_en: String,
    val disputes: Boolean,
    val distance: Int,
    val enableInstallment: Boolean,
    val enablePhoneContact: Boolean,
    val features: List<Feature>,
    val guarantees: Boolean,
    val guaranteesDesc: String,
    val hasDeposit: Boolean,
    val depositPaidUser : DepositPaidUser? ,
    val id: Int,
    val imgs: List<String>,
    val imgs3D: List<String>,
    val link3D : List<String> ,
    val influentialInformation: Boolean,
    val influentialInformationDesc: String,
    val isFavourite: Boolean,
    val lands: List<Land>? ,
    val startSaleDate: String?,
    val location: Location,
    val owner: Owner,
    val price: Float,
    val priceAvg: String,
    val priceType: String,
    val properties: List<Property>,
    val rate: Int,
    val rateCount: Int,
    val rateNumbers: Int,
    val region: Region,
    val related: Boolean,
    val saudiBuildingCode: Boolean,
    val size: Double ,
    val statistics: List<Statistic>,
    val status: String,
    val subCategory: SubCategory,
    val theAverage: Any,
    val title: String,
    val title_ar: String,
    val title_en: String,
    val totalViews: Int,
    val undocumentedRights: Boolean,
    val undocumentedRightsDesc: String,
    val updatedAt: String,
    val unitNumber: Int?,
    val units: List<Unit>,
) : Serializable